### ISSUE TITLE
getPort functions return type

### ISSUE THREAD

**Issue by mrv96** [tobiasebsen/ArtNode#10]
Hi, i see that the return type of the 3 getPort functions is uint8_t, and in case of error you return -1. Your example works becuse int implicit cast, but this is a little bit tricky. Just for a matter of semplicity, wouldn't it be better if their return type is int8_t?

**Comment by tobiasebsen** [comment]
Thanks for pointing it out. Fixed by 4d8de311c199219487a76b700b638cf17c317ba5
