### ISSUE TITLE
BasicNode example - Ethernet init fix

### ISSUE THREAD

**Issue by tommag** [tobiasebsen/ArtNode#7]
First of all, thanks for sharing your nicely written lib !

I have struggled a bit to get the Art-net discovery working because of a mistake in BasicNode example : the Ethernet initialization line should be
` Ethernet.begin(config.mac, config.ip, gateway, gateway, config.mask);`
instead of 
` Ethernet.begin(config.mac, config.ip, gateway, gateway, config.subnet);`

My Art-net subnet is set to 0 so this would set the TCP/IP subnet mask to 0 too, thus not receiving the ArtPoll broadcast packet. 

Now everything is working fine using standard 2.x.x.x Art-Net IPs.

**Comment by tobiasebsen** [comment]
Thanks @tommag !
