### ISSUE TITLE
Problem with Adafruit Neopixel

### ISSUE THREAD

**Issue by lyon470** [tobiasebsen/ArtNode#8]
### Problem with Adafruit Neopixel
Hello,
Thank you for this wonderful library.

I have a big problem with controlling Adafruit Neopixel Leds.
I want to control a strip of 60 pixels over ArtNet.

The ArtNet works fine, but i don't get to shine any of the pixels.
I use the original Adafruit Neopixel Libarary.

Can anybody help me please?

**Comment by tobiasebsen** [comment]
This sounds like an issue with the Neopixel Library and not ArtNode. You should test the NeoPixel library separately (without ArtNode) to debug it.

**Comment by lyon470** [comment]
I am sure that the Neopixel library are working because i have a Pixel test in void setup().
I'm not sure if my code can work or i have a issue in it.

**Comment by tobiasebsen** [comment]
This issue-tracker is not really intended for support questions, but can you paste your code in to https://gist.github.com and post the link?
